name: MSYS2
on: workflow_dispatch

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-qt5-base mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-make
      - name: build
        run: |
          cd Kvantum
          qmake WITHOUT_KF=YES
          qmake install
      - uses: actions/upload-artifact@v4
        with:
          name: qtct-msys2
          path: C:/Kvantum
