name: MSYS2
on: [workflow_dispatch, push]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: |
            git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-make
      - name: build
        run: |
          wget https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-qt5-base-5.15.3%2Bkde%2Br174-3-any.pkg.tar.zst --show-progress -O qt5-base.tar
          pacman -U --noconfirm qt5-base.tar
          wget https://repo.msys2.org/mingw/mingw64/mingw-w64-ucrt-x86_64-qt5-svg-5.15.3%2Bkde%2Br12-1-any.pkg.tar.zst --show-progress -O qt5-svg.tar
          pacman -U --noconfirm qt5-svg.tar
          wget https://repo.msys2.org/mingw/mingw64/mingw-w64-ucrt-x86_64-qt5-tools-5.15.3%2Bkde%2Br1-3-any.pkg.tar.zst --show-progress -O qt5-tools.tar
          pacman -U --noconfirm qt5-tools.tar
          mkdir build
          cd build
          qmake ../Kvantum/kvantum.pro WITHOUT_KF=YES WITHOUT_MANAGER=YES -spec win32-g++
          mingw32-make install
          cd C:/Kvantum/styles
          windeployqt --no-translations --no-system-d3d-compiler --no-opengl-sw --no-angle kvantum-qt5.dll
      - uses: actions/upload-artifact@v4
        with:
          name: kvantum-ucrt64
          path: C:/Kvantum

  msys2-mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            git mingw-w64-x86_64-gcc mingw-w64-x86_64-make
      - name: build
        run: |
          wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-qt5-base-5.15.3%2Bkde%2Br174-3-any.pkg.tar.zst --show-progress -O qt5-base.tar
          pacman -U --noconfirm qt5-base.tar
          wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-qt5-svg-5.15.3%2Bkde%2Br12-1-any.pkg.tar.zst --show-progress -O qt5-svg.tar
          pacman -U --noconfirm qt5-svg.tar
          wget https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-qt5-tools-5.15.3%2Bkde%2Br1-3-any.pkg.tar.zst --show-progress -O qt5-tools.tar
          pacman -U --noconfirm qt5-tools.tar
          mkdir build
          cd build
          qmake ../Kvantum/kvantum.pro WITHOUT_KF=YES WITHOUT_MANAGER=YES -spec win32-g++
          mingw32-make install
          cd C:/Kvantum/styles
          windeployqt --no-translations --no-system-d3d-compiler --no-opengl-sw --no-angle kvantum-qt5.dll
      - uses: actions/upload-artifact@v4
        with:
          name: kvantum-mingw64
          path: C:/Kvantum
